version: "3"

services:
  web:
    container_name: customerservice
    restart: always
    build: .
    ports:
       - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "27017:27017"